[package]
name = "sqlx-example-postgres-listen"
version = "0.1.0"
edition = "2021"
publish = false
workspace = "../../../"

[dependencies]
sqlx = { package = "sqlx-oldapi",  path = "../../../", features = [ "postgres", "tls" ] }
futures = "0.3.1"
tokio = { version = "1.20.0", features = ["macros"]}
