[package]
name = "sqlx-example-postgres-mockable-todos"
version = "0.1.0"
edition = "2021"
publish = false
workspace = "../../../"

[dependencies]
anyhow = "1.0"
futures = "0.3"
sqlx = { package = "sqlx-oldapi",  path = "../../../", features = ["postgres", "offline", "runtime-tokio-native-tls"] }
structopt = "0.3"
tokio = { version = "1.20.0", features = ["macros"]}
dotenvy = "0.15.0"
async-trait = "0.1.41"
mockall = "0.11"
