name: Publish workspace crates

on:
  workflow_dispatch: {}
  push:
    paths:
      - "**/Cargo.toml"
      - ".github/workflows/publish.yml"
    tags:
      - "v*"
  pull_request:
    paths:
      - "**/Cargo.toml"
      - ".github/workflows/publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Publish workspace
        run: |
          cargo publish \
          ${{ startsWith(github.ref, 'refs/tags/v') && '--dry-run' || '' }} \
           --workspace \
           --token ${{ secrets.CRATES_TOKEN }} \
           --no-default-features \
           --features runtime-actix-rustls
